### ISSUE TITLE
suggestion: createAction with just creatorFunction argument

### ISSUE THREAD

**Issue by arolson101** [piotrwitek/typesafe-actions#11]
```createAction``` called with a creatorFunction has an unused and not-DRY typeString argument.  Could it just be inferred from the return type of the creatorFunction?

E.g.:
```jsx
export declare function createAction<T extends string, AC extends (...args: any[]) => {
    type: T;
}>(creatorFunction: AC): AC & TypeGetter<T>;
```

then used like this:
```jsx
const actions = {
  ping: createAction((arg: number) => ({
    type: 'PING',
    arg,
  })),
};
```

**Comment by arolson101** [comment]
nm, I see that the implementation uses the typeString for the ```getType``` function

**Comment by piotrwitek** [comment]
@arolson101 Currently in TS (v2.6.2) it is not possible to infer the literal type of `type` property because it is widened to string, this is why the api require this additional typeString argument.
But I expect this will be handled in the future version of TypeScript and then the API will be simplified exactly the way that you expected.

**Comment by piotrwitek** [comment]
added comment to API docs: https://github.com/piotrwitek/typesafe-actions/blob/master/README.md#createaction
