### ISSUE TITLE
Export helper-types returned from public API

### ISSUE THREAD

**Issue by ecnaidar** [piotrwitek/typesafe-actions#123]
Hi, thank you for your work on this great package, actually makes redux usable with typescript.

In my project I use typescript and have a generic reducer factories and side effect functions that infer their types from action creators. 
Issue is that I am operating on the internal types from this package importing them from /dist/types and in the recent release they have changed. I know that it is my issue with an incorrect usage since those types are "internal" and are not the part of API. Currently I will be locking version to 3.1.0 

Question is what is the possible solution to that issue in you opinion? 
Should consumer write own types for parameters that would have a compliant form or such usage is entirely discouraged? 
Do you think it may be possible to make internal types available in the future?

**Comment by piotrwitek** [comment]
Hey,
Basically, you have your own library and just reusing some external types from us, so all the maintenance burden is on you. So obviously if you want some new features from upstream you'll need to refactor your code as well to be compatible (and that's why we're doing this job collectively here so people don't have to do it).

If there is some missing feature that you'd like to be included in `typesafe-action` you can always submit a proposal and will see if that is something useful to the community or not and maybe we can extend the library with your use-case. There is no other way around it.

**Comment by ecnaidar** [comment]
@piotrwitek 
Seems that there is a bit of misunderstanding of what I am talking about. What I am proposing is that types could be easier to import because they are implicitly exposed anyway. 
e.g. We have a createAsyncAction function that returns value of type AsyncActionBuilder. The type is being exposed as return value but if I want to further operate on it the only place I can import the type is internal file. 
It seems to make sense for me to have functions parameters/returns types exported along with functions.
I can work on PR for that if that something that can be added.

**Comment by piotrwitek** [comment]
Ah ok, now that makes sense :)

Sure, you can open PR, but please be careful to pick up only the types that are returned from the public API, so private types helpers are not exposed.

**Comment by strdr4605** [comment]
@piotrwitek, a possible solution for this issue is the method used by redux-saga https://github.com/redux-saga/redux-saga/blob/master/packages/core/effects/package.json
having a `type-helpers` folder in the root of npm package with a `package.json` which points to `typesafe-actions/dist/type-helpers` so the types can be imported like 
```js
import { ActionType, EmptyAC, PayloadAC } from 'typesafe-actions/type-helpers';
```

**Comment by piotrwitek** [comment]
Hey @strdr4605 
Thanks for your suggestion, perhaps you haven't noticed but all type-helpers are already exported in the public API.

```
// type-helpers
export {
  TypeConstant,
  Action,
  ActionCreator,
  Reducer,
  EmptyAction,
  PayloadAction,
  MetaAction,
  PayloadMetaAction,
  EmptyAC,
  PayloadAC,
  PayloadMetaAC,
  TypeMeta,
  ActionType,
  StateType,
  Types,
} from './type-helpers';
```

**Comment by strdr4605** [comment]
@piotrwitek, sorry, VSCode was auto importing it from `typesafe-actions/dist/type-helpers`.
