### ISSUE TITLE
Redux bindActionCreators does not work with 3.2 (ActionType is broken?)

### ISSUE THREAD

**Issue by nixxquality** [piotrwitek/typesafe-actions#124]
## Description
Since typesafe-actions 3.2, some typing error has appeared that means Redux's bindActionCreators does not work in some cases.

```typescript
export type ColorCycleAction = ActionType<typeof colorCycle>;
// ColorCycleAction is 'any'
```

## Steps to Reproduce
1. Clone https://gitgud.io/nixx/twitch-extension-buzzword-boilerplate.git
2. `cd twitch-frontend`
3. `npm install`
4. `npm run build` -> this works
5. `npm install typesafe-actions@3.2`
6. `npm run build` -> error
```
Type error: Type 'PayloadAC<ColorCycleActionTypes.CYCLE, void>' is not assignable to type '(event: MouseEvent<HTMLButtonElement, MouseEvent>) => void'.
  Types of parameters 'payload' and 'event' are incompatible.
    Type 'MouseEvent<HTMLButtonElement, MouseEvent>' is not assignable to type 'void'.  TS2322
```
The typesafe-actions in that project is 3.0, but I've verified in a private project that the issue was introduced after 3.1.
You can notice a bunch of issues pop up, but I think the source of the problem is the ActionType thing.
In my private project, for example, it is bindActionCreators that blows up.
```typescript
const mapDispatchToProps = (dispatch: Dispatch<RootAction>) => bindActionCreators(
  {
    openFile: fileActions.openFileFromInput,
    openFileFromDisk: fileActions.openFileFromDisk,
    importFile: importComponentsActions.loadFromDragAndDrop,
  },
  dispatch, // Argument of type 'Dispatch<RootAction>' is not assignable to parameter of type 'Dispatch<AnyAction>'.
);
```

**Comment by piotrwitek** [comment]
Thanks for a nice report. I'll look into this later today.

**Comment by bernardobelchior** [comment]
I am facing the same issue

**Comment by MasGaNo** [comment]
The bug here is because since 3.2, `void` is not consider as `EmptyAC`, so you get a `PayloadAC<x, void>` type for your `request` that's not compatible with `MouseEvent`.

@nixxquality  Here a workaround, is to replace `void` by `undefined` in your `twitch-frontend/src/store/colorCycle/actions.ts` file:
```ts
export const cycle = createAsyncAction(
  ColorCycleActionTypes.CYCLE,
  ColorCycleActionTypes.CYCLE_SUCCESS,
  ColorCycleActionTypes.CYCLE_FAILURE
)<undefined, string, Error>();
```
At this moment, all error should be gone.

@piotrwitek For `typesafe-actions`, I don't know what's the approach you want to have for `void`, but a quick fix could be this one in `typesafe-actions/dist/type-helpers.d.ts`:
```ts
export declare type ActionBuilderConstructor<T extends StringType, TPayload extends any = undefined, TMeta extends any = undefined> = 
    [TMeta] extends [undefined] 
        ? [TPayload] extends [undefined] 
            ? unknown extends TPayload 
                ? PayloadAC<T, TPayload> 
                : unknown extends TMeta 
                    ? PayloadMetaAC<T, TPayload, TMeta> 
                    : EmptyAC<T> 
            : TPayload extends void // Just add this condition
                ? EmptyAC<T> 
                : PayloadAC<T, TPayload> 
        : PayloadMetaAC<T, TPayload, TMeta>;
```
Or if you want to have a generic way:
```ts
export declare type IsEmpty<T> = T extends undefined ? never : T extends void ? never : T;
export declare type ActionBuilderConstructor<T extends StringType, TPayload extends any = undefined, TMeta extends any = undefined> = 
    [TMeta] extends [undefined] 
        ? [IsEmpty<TPayload>] extends [never] 
            ? unknown extends TPayload 
                ? PayloadAC<T, TPayload> 
                : unknown extends TMeta 
                    ? PayloadMetaAC<T, TPayload, TMeta> 
                    : EmptyAC<T> 
            : PayloadAC<T, TPayload> 
        : PayloadMetaAC<T, TPayload, TMeta>;
```

**Comment by piotrwitek** [comment]
Thanks for investigation, I just returned from vacations, I'll take a look in the evening

**Comment by piotrwitek** [comment]
@MasGaNo @nixxquality Thanks for your reports based on them I have come to the conclusion that changing `void` constraint to `undefined` was a breaking change and should follow with a major version bump instead with a minor and a migration guide.

In order to fix that I will publish a fix for v3 with a suggested solution by @MasGaNo to bring back the backward compatibility, and then I'll switch to a new major version v4, that will only support `undefined` constraint. Using `undefined` is superior and I don't see any reason to support `void` any longer as it only adds complexity to the codebase, migration to v4 will be very simple - change all `void` type parameters in action creators to `undefined`.

**Comment by nixxquality** [comment]
In my opinion, `void` makes it clear that no argument should be supplied whereas `undefined` sounds like undefined behaviour.
I  think the correct terminology is worth the extra work, but it's your call in the end.

**Comment by piotrwitek** [comment]
I do not agree, `void` was incorrect terminology, it is only valid in the context of expressions when you want to change a function return, and IMO it shouldn't be used in other not related contexts to avoid confusion. `undefined` is correct in case of the empty function argument.

You can learn more about the semantics of void operator here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void

**Comment by nixxquality** [comment]
I wasn't aware that Javascript has that usage of `void`, but do note that TypeScript has its own definition of it.
https://www.typescriptlang.org/docs/handbook/basic-types.html#void
> void is a little like the opposite of any: the absence of having any type at all. You may commonly see this as the return type of functions that do not return a value

This lines up with the usage of `void` in other languages, such as C.

The ambiguity is weird, but it's not the only place where TypeScript and Javascript have different meanings of things...

**Comment by piotrwitek** [comment]
Fixed in v3.4.0 release

**Comment by piotrwitek** [comment]
@nixxquality good point but nevertheless I'm maintaining this library for a few years now and I know that this will be a big hindrance in the long run for me, I made this errors in the past and I would rather focus on new features than such details that IMO have minimal impact for DX, it's just a matter to learn a new simple convention: use `undefined` instead of `void`

**Comment by piotrwitek** [comment]
Also, it makes it symmetric with a new feature which is an optional parameter when you use union like this `number | undefined`.

**Comment by lukyth** [comment]
For the no parameter type, what do you think about using `never` comparing to `undefined`?

FYI: I have been using `never` for this case since `2.x`.

**Comment by nixxquality** [comment]
`never` is supposed to be used in cases where the function will never return; for example, something inside it always throws an error.
https://www.typescriptlang.org/docs/handbook/basic-types.html#never
