### ISSUE TITLE
Include the returntypeof helper in this library

### ISSUE THREAD

**Issue by sylvanaar** [piotrwitek/typesafe-actions#13]
Using this library tends to require the returntypeof helper, but that is in another library, which is fine, but that one broke for Typescript 2.7 which makes me think that maybe returntypeof belongs with this code more, or at least in addition.

**Comment by sylvanaar** [comment]
Didn't notice it was there.

**Comment by piotrwitek** [comment]
it's for backward compatibility, but please be careful as it's not public so it might be removed in the future

**Comment by sylvanaar** [comment]
You should really keep it with this library, since this action creator design requires it, and I'd rather not have to add another library with things I don't need just to use this one. Just my 2 cents. Thanks for your hard work!

**Comment by piotrwitek** [comment]
I agree with you on the last point. But please bear in mind that this is really a temporary solution and soon it will be replaced by type inference, the only thing that is blocking me right now is the public release of conditional type with generic inference that is already merged with master.
Then I plan to reimplement the API so you will be able to get a union type using type-level mapped type instead of runtime `returntypeof` helper.

**Comment by sylvanaar** [comment]
Oh, we won’t need it with TS 2.8? I didn’t realize that. That’s really great news! Do you already have a branch for that?

**Comment by piotrwitek** [comment]
Not yet, but I'm gonna put it out soon on the next branch

Pozdrawiam,
Piotr Witek

2018-02-05 16:30 GMT+01:00 Jon S Akhtar <notifications@github.com>:
