### ISSUE TITLE
Is catchError(pipe(fetchTodosAsync.failure, of)) from the doc a legit syntax?

### ISSUE THREAD

**Issue by goldenbearkin** [piotrwitek/typesafe-actions#177]
I use the syntax `catchError(pipe(fetchTodosAsync.failure, of))` follow the [doc](https://github.com/piotrwitek/typesafe-actions#with-redux-observable-epics), but it doesn't work. I love the syntax, it is so clear, but is it legit?

**Comment by piotrwitek** [comment]
Hi @goldenbearkin, of course, it is :)

Why wouldn't you try to git pull the repo, and open the sandbox project in your IDE, there is a reason I have added it there :)

**Comment by piotrwitek** [comment]
@goldenbearkin I believe it was working in the earlier version of TypeScript because the default type param was `any`. Not long ago it was changed to `unknown` in 3.5 or something, and now it is causing a type error in strict mode.

Unfortunately, it will not work anymore, I'll update the documentation.

Thanks for reporting.

**Comment by piotrwitek** [comment]
Actually there is more, it seems the root issue is in the rxjs types because `of` function is overloaded and it doesn't work well with pipe or compose.
IF you change of declaration to this declaration, it will work:
```
export declare function of<T>(a: T): Observable<T>;
```
Alternatively `from` is working fine:
```
catchError(
  pipe(
    loadTodosAsync.failure,
    Array,
    from,
  )
)
```

Anyway, as a best alternative, I would just create a custom catchError wrapper to handle it more elegantly and actually there is a ticket for it somewhere in the repo that is WIP.
