### ISSUE TITLE
What is the future of the project?

### ISSUE THREAD

**Issue by quolpr** [piotrwitek/typesafe-actions#242]
Hey, guys! I wanted to ask this question in the spectrum.chat(as GitHub Pull Request mentioned me), but it seems not so active. So I want to ask it here.

So, my main question - what is the key benefit of typesafe-actions in front of redux-toolkit? And what is the near future of this project? Do you have worries that typesafe-actions will not be in demand because of redux-toolkit?

I am very thankful for the library you made - it is a really great job. I appreciate the time you put into this project. And I am asking this question to make sure will it be the right decision(in terms of maintainability of the library) to take typesafe-actions in my future projects.

Thanks for understanding.

**Comment by piotrwitek** [comment]
Hey,

The biggest difference is that this project is "typescript first" and always will be. The biggest effort is put not into the logic of the library, but into the type-safety.

You can be sure that this library will never break your TS project because of its unique **type unit tests**.

There is a lot on the plate for the near future, especially in the area of minimizing the boilerplate.

If you have some more specific questions let me know.

**Comment by quolpr** [comment]
Thank you for your explanation! That what I was needed to hear. Long Live typesafe-actions 🙂
