### ISSUE TITLE
is here a way to use `redux-promise-middleware` together?

### ISSUE THREAD

**Issue by AtrisMio** [piotrwitek/typesafe-actions#28]
I want to use `redux-promise-middleware` and this lib in my project, but I don't know is here a way to assert action when I use `redux-promise-middleware`, and assert type T of `Promise<T>`?

`redux-promise-middleware` will re-dispatch three actions, with suffix '_PENDING', '_FULFILLED', '_REJECTED'.

**Comment by piotrwitek** [comment]
Hi, I would need more thorough explanation to your problem. Could you please provide some reference implementation of your idea with brief explanation for each part.

**Comment by AtrisMio** [comment]
https://github.com/pburtchaell/redux-promise-middleware

the `redux-promise-middleware` is a redux middleware, when the user dispatch an promised action (the payload is a promise). The middleware will block this action, and re-dispatch an action of which type is end with `_PENDING` . When the promise fulfilled or rejected, it will dispatch the result in an action of which type is end with `_FULFILLED` or `_REJECTED`.

**Comment by piotrwitek** [comment]
TypeScript cannot achieve what you're asking, because when you add a suffix literal type (`_REJECTED`) to any other literal type (`SOME_TYPE`), it will always widen to the super-type of literal which is `string`. Because of this you have to declare required literal type upfront only then you can use it with `tagged union types`.
